unicodeveloper/awesome-nextjs

README.md
Added NextSimpleStarter under a new category(Boilerplates/Starters) #1
=> Add NextSimpleStarter

README.md
Added new boilerplate - https://github.com/sly777/ran
=> Add RAN boilerplate

README.md
https://github.com/sindresorhus/awesome/pull/988#issuecomment-315893282
What better description can be give to [RAN](https://github.com/sly777/ran) ?
=> Follow Rules

README.md
I am developing a tool for Trello and I want to share it with the entire NextJs community.
[juliandavidmr/TrelloResume](https://github.com/juliandavidmr/TrelloResume)
Thanks 😊
=> Add app: Trello Resume

README.md
This article was popular on HackerNoon and some folks suggested I add it here.
=> Adding an article on adding payment to nextjs

README.md
I wrote an article for using Next.js on Firebase.
Thanks for the sweet resource! :smile:
=> Add Firebase example

README.md
The main idea behind this example is to handle the sessions on the server, letting you
validate if the user is logged before the view is rendered, as you know or now you know to access to local storage on server render you must do `componentDidMount` so this example prevent the render before the validation.
=> Server auth with JWT

README.md
Hi.
I'd like to propose my latest project.
Cheers.
=> Add phox to list of boilerplates

README.md
sorry, I screwed up the list … 🤦‍♂️
=> fix the boilerplate list

README.md
Hey, thanks for the great list. I have added a few more video tutorials and presentations.
=> Added more video tutorials and the appropriate menu link

README.md
Add DS in apps - https://github.com/divyenduz/ds
=> Add DS app to apps

README.md
very useful article for Russian speakers
=> Add article in Russian language

README.md
awesome article for awesome next
=>  Add article from hackernoon

README.md
The link to the repository is https://github.com/MustansirZia/next-express-bootstrap-boilerplate.
=> Added next-express-bootstrap-boilerplate to boilerplates.

README.md
Adding Boilerplates nextjs-in-firebase-with-bootstrap with live preview site link
=> Adding Boilerplates nextjs-in-firebase-with-bootstrap

README.md
Hi, I created feature-packed example of blog, that you can do with Next.js and other cool technologies. Would be glad if it will be listed here.
https://github.com/suevalov/next-blog-firestore
=> Added next-blog-firestore to Boilerplates section

README.md
Added Next Boilerplate to boilerplates section.
=> add Next Boilerplate to boilerplates section

README.md
Link to [book](https://leanpub.com/hands-on-nextjs)
=> Added Hands On Next.js  book to Books category

README.md
Added a link to the "Urteile & Gesetze" GitHub Project. The Project is written with nextjs and is under the GPLv3 license
=> Added Urteile & Gesetze

README.md
- https://github.com/joaopaulomoraes/nextjs-with-redux-and-material-ui
=> feat: Added a boilerplate with redux-wrapper and material-ui

README.md
Adds [serverless framework plugin](https://github.com/danielcondemarin/serverless-nextjs-plugin) for deploying next apps
=> Add serverless-nextjs-plugin

README.md
Added an article that shows how to use Next.js for e-commerce!
=> Nextjs E-commerce

README.md
This is a library that creates terraform configuration and lambdas from nextjs files.
=> Add terraform nextjs plugin - serverless

README.md
While visiting it redirects to 404 also another nextgram app exists in the list
=> remove nextgram as its repo doesnt exist

README.md
Thought people might want to know how to use the Ghost API with Next.js 👩‍💻
=> Add Working with Ghost and Next.js

README.md
I wrote an article about how to install the popular [Tailwind CSS](https://tailwindcss.com) framework in a Next.js project. It might be useful to others!
=> Add Tailwind article

README.md
Add `next-session` - A session middleware for Next.js
=> Add next-session

README.md
https://github.com/lucleray/next-purgecss
=> Add next-purgecss

README.md
A basis for reducing the configuration of your projects with nextJS, best development practices and popular libraries in the developer community.
=> feat: Add new Boilerplate - react-next-boilerplate

README.md
https://github.com/Sebastp/Next-react-graphql-apollo_Boostrap
title; Next Graphql Apollo Typescript_Boostrap - Pobocha
=> Added another Boilerplates

README.md
* https://njt.now.sh
* https://github.com/kachkaev/njt
* https://twitter.com/kachkaev/status/1206204515126595586
=> Add njt (npm jump to) to Apps 🐸

README.md
Wanted to share my boilerplate with the following features:
- Typescript
- Styled Components
- Redux/React-redux
- React-Testing-Library
- ESLint
- Fontawesome
=> Add another nextjs boilerplate to README

README.md
Flaviocopes wrote a book on Next.js on server-side rendering.
=> Build your own next.js project with Flaviocopes

README.md
See https://github.com/UnlyEd/next-right-now
=> Add Next Right Now boilerplate

README.md
There wasn't an easy way to get the user's language universally, until now
https://github.com/UnlyEd/universal-language-detector
Demo: https://universal-language-detector.now.sh/
=> Add universal-language-detector

README.md
https://hackernoon.com/next-js-react-server-side-rendering-done-right-f9700078a3b6 is unavailable
=> Removing dead article

README.md
[flow-middleware](https://github.com/piglovesyou/flow-middleware) is a tool to create request handlers from Express middlewares. Without re-implementing all the Cookie, Session or OAuth middlewares and adapters for Next.js again, users can start using them today.
=> Add flow-middleware

README.md
next-iron-session is a stateless session utility for Next.js
Session data is stored client-side in Secured, HttpOnly signed and encrypted cookies.
This is the same technique used by Ruby On Rails (https://guides.rubyonrails.org/security.html#session-storage)
More information on https://github.com/vvo/next-iron-session
=> feat(Extensions): add next-iron-session

README.md
Github repo: https://github.com/tudorconstantin/knests/
Introductory blog post: https://programming.tudorconstantin.com/2020/05/the-knests-stack.html
=> Add The Knests Stack under Boilerplates

README.md
changed the naming to the new Vercel 
and updated the links for community
=> changed zeit now naming

README.md
Open source application with Auth0 / GraphQL integrated with NextJS  https://github.com/poulainv/tottem
=> Add Tottem

README.md
=> Add Mastering Next.js 🏆

README.md
Adding "Next.js in Action" from Manning.
=> Added book "Next.js in Action"

README.md
Added in Next-SMRT Boilerplate
=> Added in Next-SMRT

README.md
The easiest way to translate your NextJs apps.
=> next-i18next

README.md
Broken link, couldn't find the same repo in a quick search
=> remove boilerplate Apollo-Nextjs-GraphQL

README.md
Full-featured forum-like app with Postgres, Typescript, Redux, Emotion, and out-of-the-box Auth support.
=> Added 'Next-Postgres-With-Typescript' boilerplate

README.md
=> Added: Cosmic static blog starter

README.md
This commits adds a Newsletters section and two newsletters:
- https://nextjsnews.com
- https://nextjsnotes.com
cc @dbredvick
=> feat(sections): add Newsletters & two newsletters

README.md
This is a new app that I created using Next.js
=> add SlowTVMap to Apps section

README.md
Hey there 👋🏾.
This is my first contribution here and there's a huge chance I might miss something. 
Please give feedback on the pull request format if it's wrong.
Thanks, alot.
=> add Nextjs-starter-peacock

README.md
This is about my course [Bulletproof Next](https://getstarted.sh/bulletproof-next). But I'm not sure where this content should go.
=> Add a link to my always FREE Next.js course :D

README.md
Hi, Next.js News is now monthly
=> docs(newsletters): Next.js News bi-weekly -> monthly

README.md
Adds [Using Feature Flags in Next.js](https://medium.com/frontend-digest/using-feature-flags-in-next-js-c5c8d0795a2?source=friends_link&sk=d846a29f376acf9cfa41e926883923ab) to the articles list.
=> Add Feature Flags to articles

README.md
add next-transpile-modules https://github.com/martpie/next-transpile-modules
=> docs: add next-transpile-modules 

README.md
Repo: https://github.com/pankod/superplate
Docs: https://pankod.github.io/superplate/
=> Add superplate

README.md
Add powerful Next.js and Tailwind CSS boilerplate. ✨
=> feat: add Kaminari template: https://github.com/lucky-chap/kaminari

README.md
@unicodeveloper Please let me know if there are any changes needed. Thanks.
=> Add Chargebee Subscription NextJS Starter SAAS Template

README.md
Broken link, couldn't find the same repo in a quick search.
=> removed broken link

README.md
An enterprise-grade Next.js boilerplate for high-performance, maintainable apps. Packed with features like Tailwind CSS, TypeScript, ESLint, Prettier, testing tools, and more to accelerate your development.
=> Add Next.js Enterprise project to boilerplates list

README.md
[next-api-decorators](https://github.com/storyofams/next-api-decorators) contains a collection of decorators to create typed Next.js API routes, including easy request validation and transformation.
=> Add next-api-decorators to extensions

README.md
I found this repo very useful and thought to add my contribution here. 
A very friendly and handy book called **"Real World Next js"** book has been added. Kindly accept this under **Hacktoberfest** label
=> Added Next.js book in README.md file

README.md
https://github.com/BearStudio/start-ui-web
=> Add 🚀 Start UI [web]

README.md
We recently published an article on Next.js performance that I think would be a good fit for this list. Goes through a lot of topics like static/server-side rendering, image optimization, and third-party performance impact.
=> Add guide to Next.js performance
