unicodeveloper/awesome-nextjs

README.md

The main idea behind this example is to handle the cookies when the view is render on the server side. Because on the server side it can't be something like `document.cookie` because it can't access to the `document` so the idea is to have a middleware on the server of `Next.js` that will get the cookie and set it in `res.locals` making it accessible from the view with `static getInitialProps({ res })`

Cookie handler with server render

---

README.md

I'm working on this project so people can migrate from redux/postcss stacks more easily.

add nextjs-redux-starter to boilerplates 

---

README.md

TypeScript integrated with NextJS@5(released yesterday)
It has been developing since NextJS@2

Add NextJS TypeScript Starter Kit

---

README.md

and update NextJS TypeScript Starter Kit description(owner)

Add Typescript monorepo next example,

---

README.md

Our documentation uses a specific URL pattern to ensure people are directed to the latest version of our docs, hence the removal of `v2/` in this case. Thanks!

Ghost URL Typo

---

README.md

`nextjs-mongodb-app` differs to other in the way that it is much simpler, with no usage of custom server, no Redux (replaced with native Context API).
Features authentication, some profile (update profile, picture), and more to be added in the future.

Add nextjs-mongodb-app as a boilerplates

---

README.md

Most boilerplates use the Now 1.0 server style instantiating a nodejs server, this follows the new style for 2.0 and adds some niceties by default

Add Now 2.0 example

---

README.md

add [next-cookie](https://github.com/tokuda109/next-cookie) to extensions.
npm page is [here](https://www.npmjs.com/package/next-cookie).

Add next-cookie to extensions

---

README.md

Thank you for your good repo containing a lot of good stuff. I'd like to add a boilerplate about how to deploy a Next.js app to AWS lambda.

add boilerplate, How to deploy to AWS Lambda

---

README.md

https://github.com/pd-smith/next-express-babel

Add Boilerplate for NextJS app using Babel to Transpile Express and Next

---

README.md

next-connect is a method routing and middleware layer for Next.js. Powered by trouter. This allows the use of Express middleware without a custom server.
(Recreated #120 since fork is lost)

Add next-connect to extensions

---

README.md

Added a Next.js-powered boilerplate for a developer blog. The design process is written up [here](https://news.ycombinator.com/item?id=23309002) and the HN discussion is [here](https://news.ycombinator.com/item?id=23309002).

Added Next.js developer blog boilerplate

---

README.md

I semi-recently released https://github.com/lone-cloud/next-deploy which allows for effortless deploys to github pages and AWS (serverless).

adding next-deploy under extensions

---

README.md

[`next-joi`](https://github.com/codecoolture/next-joi) is a simple extension to take advantage of [`joi`](https://github.com/sideway/joi)'s schema validator when developing with Next.js API Routes.

Add next-joi extension

---

README.md

I recently released a new boilerplate to build blogs with only Netlify stacks.

Add Next.js and Netlify blogging template

---

README.md

Zeit's name change to Vercel should be updated. The links weren't broken but I figured it wouldn't do harm to make this quick change.
Also, I removed Next Plugins from the list since they were recently deprecated in favor of the Next.js [monorepo](https://github.com/vercel/next.js)

Switch to Vercel GitHub organization instead of Zeit

---

README.md

The playlist is from the official Vercel youtube channel. https://www.youtube.com/playlist?list=PLBnKlKpPeagnT2Cmv4giCbosfrbKnuYTD
Looks like most of the videos, if not all are uploaded to the channel.

Add Nextconf 2020 playlist to videos categegory

---

README.md

Repository contains additional server on express for generate and regenerate sitemaps and robots.txt files into public directory by STRAPI request

Added next-strapi-sitemap repository link

---

README.md

I updated the broken link to hands-on next.js book. Although it links to a paid version of the book since I could not get the free one.

Updated Broken link to book in README.md

---

README.md

The Hydrogen starter template URL has been changed recently, so please accept this PR so it's not going to 404 page. Thank you.

Redirect 404 URL for boilerplates

---

README.md

UseSIWE is the easiest way to add Sign-in with Ethereum to your app.
https://github.com/random-bits-studio/use-siwe

Add UseSIWE to the list of extensions

---

README.md

Hi, thanks for creating this. I've proposed an addition to the community section - Vercel maintains an official community site that is a great resource for getting help with Next.js issues and questions. It's not a formal support channel, but Vercel engineers do hang out and answer questions from time to time. It would be great to make this more widely known so folks can get help when they need it.

Add Vercel community
